title       = "mlb"
baseURL     = "https://mlb-cli.tamnd.com/"
description = "A command line for mlb."
contentDir  = "content"
outputDir   = "public"
theme       = "tago-doks"
syntaxHighlight = "true"

[params]
github = "https://github.com/tamnd/mlb-cli"
